### ISSUE TITLE
Readme.md image

### ISSUE THREAD

**Issue by mamori017** [masahikomori/timeSignal#1]
![timesignal](https://cloud.githubusercontent.com/assets/7507701/20861633/1f1cbb70-b9d8-11e6-8246-6bad395b6f6a.png)

**Comment by masahikomori** [comment]
![1](https://cloud.githubusercontent.com/assets/7507701/21545802/b691174a-ce1d-11e6-9d22-31a57be0a67a.png)
![2](https://cloud.githubusercontent.com/assets/7507701/21545806/bc4cc95e-ce1d-11e6-9c34-6305418a57d8.png)

**Comment by masahikomori** [comment]
![3](https://cloud.githubusercontent.com/assets/7507701/21546458/3c69287c-ce22-11e6-8fc8-fe9396b8d105.png)
![4](https://cloud.githubusercontent.com/assets/7507701/21546459/3f99d3a2-ce22-11e6-961e-963f6a838858.png)

**Comment by mamori017** [comment]
![1](https://cloud.githubusercontent.com/assets/7507701/21547039/e333e724-ce26-11e6-8014-26aa8ad90928.png)
![2](https://cloud.githubusercontent.com/assets/7507701/21547042/e6004560-ce26-11e6-8015-7378d2c065e5.png)
![3](https://cloud.githubusercontent.com/assets/7507701/21547044/e8ffc13c-ce26-11e6-99c4-234996eaa541.png)
![4](https://cloud.githubusercontent.com/assets/7507701/21547048/eab7100c-ce26-11e6-8cee-24b7ce297cba.png)
